"use strict";
/* Core app logic — Phase 2 split from index.html */
const APP_VERSION="5.5.0"; const STORE="specialtyJobCompareCompleteV5";
const SCORE_META=[["clinicalFit", "Clinical Fit", "20%", "🩺", ["Clinical model matches skillset", "Appropriate patient complexity", "Infrastructure supports the work", "Referral/patient base is credible", "Low mismatch between advertised and actual duties"]], ["compFit", "Compensation Upside", "20%", "💰", ["Strong base/guarantee", "Clear productivity formula", "Benchmarks compare favorably", "Bonuses/equity are realistic", "No hidden cap/clawback"]], ["lifestyleFit", "Lifestyle Fit", "15%", "🏡", ["Reasonable commute", "Schedule is family-compatible", "Call burden is acceptable", "Admin/inbox time is manageable", "Vacation/flexibility are clear"]], ["riskFit", "Risk Safety", "15%", "🛡️", ["Noncompete is limited", "Tail coverage is clear", "Termination terms are fair", "Repayment obligations are reasonable", "Contract language is transparent"]], ["strategicFit", "Strategic Fit", "15%", "📈", ["Builds long-term career value", "Market position is strong", "Growth/leadership path exists", "Brand/reputation helps future options", "Partnership/equity path is credible"]], ["collabFit", "Collaborative Fit", "15%", "🤝", ["Physician culture is healthy", "APP/team model is clear", "Referral relationships are aligned", "Leadership communicates well", "Specialty-specific collaboration is supported"]]];
const CATEGORIES=[["summary","Summary"],["compensation","Compensation"],["benchmark","Offer vs benchmark"],["equity","Partnership/ancillary"],["app","APP supervision"],["quality","Quality bonus"],["volume","Volume"],["lifestyle","Lifestyle"],["risk","Risk/contract"],["collaboration","Collaboration"],["proscons","Pros/cons"]];
const TEXT_FIELDS=["name","location","jobType","status","region","compModel","call","equityTimeline","equityType","equityNotes","appCompModel","appNotes","qualityDifficulty","qualityNotes","pros","cons","followUp"];
const NUM_FIELDS={baseSalary:[0,5000000],wrvuRate:[0,10000],wrvuThreshold:[0,10000000],expectedWrvu:[0,10000000],bonusCap:[0,5000000],signOn:[0,2000000],commute:[0,600],callPay:[0,2000000],equityAnnualIncome:[0,5000000],equityBuyIn:[0,10000000],equityOwnership:[0,100],appCount:[0,200],appAnnualComp:[0,2000000],qualityBonusMax:[0,2000000],qualityBonusExpected:[0,2000000]};
const BOOL_FIELDS=["hasEquity","hasAppSupervision","hasQualityBonus"];
const BENCH_TEXT=["region","source","setting","notes"];
const BENCH_NUM={year:[2000,2100],compP25:[0,10000000],compP50:[0,10000000],compP75:[0,10000000],compP90:[0,10000000],signOnP50:[0,2000000],callPayP50:[0,2000000],prodP25:[0,10000000],prodP50:[0,10000000],prodP75:[0,10000000],prodP90:[0,10000000],compPerUnitP50:[0,10000],compPerUnitP75:[0,10000],appSupervisionP50:[0,2000000],qualityBonusP50:[0,2000000],qualityBonusP75:[0,2000000]};
const forbiddenKeys=new Set(["__proto__","prototype","constructor"]);
let state={version:APP_VERSION,settings:{autosave:true,history:true,encryption:false},data:{}}, currentSpec=null, selectedJobs=new Set(), selectedCats=new Set(["summary","compensation","benchmark"]), saveTimer=null, lastFocus=null, encryptionPassword="", lastSnapshot={}, abortController=new AbortController();
const signal=abortController.signal;
function $(id){return document.getElementById(id)}
function uid(){return (crypto.randomUUID?crypto.randomUUID():"id-"+Date.now()+"-"+Math.random().toString(16).slice(2))}
function sanitize(v,max=2000){return String(v??"").replace(/[\x00-\x1f\x7f]/g," ").replace(/[<>]/g,c=>c==="<"?"‹":"›").slice(0,max).trim()}
function safeNum(v,min=0,max=Infinity,fallback=0){const n=Number(v); if(!Number.isFinite(n)) return fallback; return Math.min(max,Math.max(min,n))}
function cleanPlainObject(obj){if(!obj||typeof obj!=="object"||Array.isArray(obj)) return {}; const out=Object.create(null); for(const [k,v] of Object.entries(obj)){if(forbiddenKeys.has(k)) continue; out[k]=v} return out}
function e(tag,o={},kids=[]){const n=document.createElement(tag); for(const [k,v] of Object.entries(o)){if(v===undefined||v===null) continue; if(k==="className") n.className=v; else if(k==="textContent") n.textContent=String(v??""); else if(k==="hidden") n.hidden=!!v; else if(k==="checked") n.checked=!!v; else if(k==="value") n.value=v??""; else if(k==="dataset") Object.assign(n.dataset,v||{}); else if(k==="style"){ if(typeof v==="string") n.style.cssText=v; else if(v&&typeof v==="object") Object.assign(n.style,v); } else if(k==="ariaPressed") n.setAttribute("aria-pressed",String(v)); else if(k==="ariaHidden") n.setAttribute("aria-hidden",String(v)); else if(k==="ariaSelected") n.setAttribute("aria-selected",String(v)); else if(k==="ariaLabel") n.setAttribute("aria-label",String(v)); else if(k==="htmlFor") n.htmlFor=v; else if(k.startsWith("on")&&typeof v==="function") n.addEventListener(k.slice(2),v,{signal}); else if(k in n){try{n[k]=v}catch{n.setAttribute(k,String(v))}} else n.setAttribute(k,String(v))} kids.forEach(c=>n.append(c instanceof Node?c:document.createTextNode(String(c??"")))); return n}
function clear(n){while(n.firstChild)n.removeChild(n.firstChild)}
function money(n){n=safeNum(n,0,Infinity,0); return n?n.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}):"TBD"}
function num(n){n=safeNum(n,0,Infinity,0); return n?n.toLocaleString():"TBD"}
function setStatus(txt,cls){if(typeof window.__premiumSetStatus==="function") return window.__premiumSetStatus(txt,cls); const s=$("saveStatus"); if(s){s.textContent=txt; s.className="status-pill "+cls}}
function toast(msg,type){if(typeof window.__premiumToast==="function") return window.__premiumToast(msg,type); const t=$("toast"); if(!t) return; t.textContent=msg; t.className="toast show"+(type?" toast-"+type:""); setTimeout(()=>t.classList.remove("show"),3500)}
function refreshAfterMutation(opts){if(typeof window.__p1Render==="function"){if(opts&&opts.all) window.__p1Render({all:true}); else window.__p1Render(Array.isArray(opts)?{views:opts}:undefined)} else renderCore()}
function specState(key=currentSpec){if(!state.data[key]) state.data[key]={leads:[],benchmarks:[],history:[]}; return state.data[key]}
function defaultLead(x={}){let l={id:uid(),name:"",location:"",jobType:"Unknown",status:"Researching",region:"National",compModel:"Unknown",baseSalary:0,wrvuRate:0,wrvuThreshold:0,expectedWrvu:0,signOn:0,commute:0,call:"Unknown",callPay:0,hasEquity:false,equityAnnualIncome:0,equityBuyIn:0,equityTimeline:"",equityOwnership:0,equityType:"",equityNotes:"",hasAppSupervision:false,appCount:0,appCompModel:"Unknown",appAnnualComp:0,appNotes:"",hasQualityBonus:false,qualityBonusMax:0,qualityBonusExpected:0,qualityDifficulty:"Unknown",qualityNotes:"",clinicalFit:5,compFit:5,lifestyleFit:5,riskFit:5,strategicFit:5,collabFit:5,pros:"",cons:"",followUp:"",checklist:{},volume:{},diligence:{}}; Object.assign(l,cleanPlainObject(x)); return cleanLead(l)}
function cleanLead(obj){obj=cleanPlainObject(obj); const l={id:sanitize(obj.id||uid(),80)}; TEXT_FIELDS.forEach(k=>l[k]=sanitize(obj[k],2000)); for(const [k,[min,max]] of Object.entries(NUM_FIELDS)) l[k]=safeNum(obj[k],min,max,0); BOOL_FIELDS.forEach(k=>l[k]=!!obj[k]); SCORE_META.forEach(([k])=>l[k]=safeNum(obj[k],1,10,5)); l.checklist=cleanPlainObject(obj.checklist); l.volume=cleanPlainObject(obj.volume); l.diligence=cleanPlainObject(obj.diligence); if(currentSpec&&SPECIALTIES[currentSpec]){SPECIALTIES[currentSpec].checklist.forEach(item=>{let v=sanitize(l.checklist[item]||"Unknown",20); l.checklist[item]=["Yes","No","Unknown"].includes(v)?v:"Unknown"}); SPECIALTIES[currentSpec].volume.forEach(item=>{l.volume[item]=sanitize(l.volume[item]||"",120)}); const grouped=EXPANDED_QUESTIONS[currentSpec]||{}; Object.entries(grouped).forEach(([group,qs])=>{(Array.isArray(qs)?qs:[]).forEach(q=>{const key=questionKey(group,q); l.diligence[key]=sanitize(l.diligence[key]||"",2000)})})} return l}
function cleanBenchmark(obj){obj=cleanPlainObject(obj); const b={id:sanitize(obj.id||uid(),80)}; b.region=sanitize(obj.region||"National",80); b.source=sanitize(obj.source||"",120); b.setting=sanitize(obj.setting||"All",80); b.notes=sanitize(obj.notes||"",2000); for(const [k,[min,max]] of Object.entries(BENCH_NUM)) b[k]=safeNum(obj[k],min,max,0); return b}
function bonusUnits(l){if(!l.expectedWrvu) return 0; if(!l.wrvuThreshold) return l.expectedWrvu; return Math.max(0,l.expectedWrvu-l.wrvuThreshold)}
function bonus(l){if(!l.wrvuRate) return 0; let b=bonusUnits(l)*l.wrvuRate; const cap=safeNum(l.bonusCap||state.settings?.bonusCapAnnual,0,5000000,0); if(cap>0) b=Math.min(b,cap); return b}
function productivityNote(l){if(!l.wrvuThreshold||!l.expectedWrvu) return ""; if(l.expectedWrvu<l.wrvuThreshold) return "Below threshold by "+num(l.wrvuThreshold-l.expectedWrvu)+" units — bonus $0 unless contract credits carryforward"; if(l.bonusCap&&bonusUnits(l)*l.wrvuRate>l.bonusCap) return "Productivity bonus capped at "+money(l.bonusCap); return ""}
function recurringComp(l){return l.baseSalary+bonus(l)+l.callPay+(l.hasEquity?l.equityAnnualIncome:0)+(l.hasAppSupervision?l.appAnnualComp:0)+(l.hasQualityBonus?l.qualityBonusExpected:0)}
function firstYearComp(l){return recurringComp(l)+safeNum(l.signOn,0,Infinity,0)}
function total(l){return recurringComp(l)}
function score(l){const w={clinicalFit:.2,compFit:.2,lifestyleFit:.15,riskFit:.15,strategicFit:.15,collabFit:.15}; let s=0; Object.keys(w).forEach(k=>s+=safeNum(l[k],1,10,5)*w[k]); return Math.round(s*10)}
function textEncoder(){return new TextEncoder()}
function textDecoder(){return new TextDecoder()}
function b64(buf){return btoa(String.fromCharCode(...new Uint8Array(buf)))}
function unb64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function hasWebCrypto(){return !!(window.crypto&&crypto.subtle&&crypto.getRandomValues)}
function simpleChecksum(str){let h=2166136261; for(let i=0;i<str.length;i++){h^=str.charCodeAt(i); h=Math.imul(h,16777619)} return "fnv1a-"+(h>>>0).toString(16)}
async function sha256(str){if(hasWebCrypto()){const buf=await crypto.subtle.digest("SHA-256",textEncoder().encode(str)); return b64(buf)} return simpleChecksum(str)}
async function deriveKey(password,salt){if(!hasWebCrypto()) throw new Error("Web Crypto is not available in this browser/context. Host over HTTPS or disable encryption."); const material=await crypto.subtle.importKey("raw",textEncoder().encode(password),"PBKDF2",false,["deriveKey"]); return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:150000,hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
async function encryptText(text,password){const salt=crypto.getRandomValues(new Uint8Array(16)), iv=crypto.getRandomValues(new Uint8Array(12)), key=await deriveKey(password,salt); const data=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,textEncoder().encode(text)); return {encrypted:true,alg:"AES-256-GCM",salt:b64(salt),iv:b64(iv),data:b64(data)}}
async function decryptPkg(pkg,password){const key=await deriveKey(password,unb64(pkg.salt)); const dec=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(pkg.iv)},key,unb64(pkg.data)); return textDecoder().decode(dec)}
async function makePackage(){const payload={version:APP_VERSION,createdAt:new Date().toISOString(),state}; const text=JSON.stringify(payload); const checksum=await sha256(text); return {version:APP_VERSION,checksum,payload}}
async function saveNow(){try{setStatus("Saving…","saving"); const pkg=await makePackage(); let text=JSON.stringify(pkg); if(state.settings.encryption){if(!encryptionPassword) throw new Error("Encryption password required in Settings"); text=JSON.stringify(await encryptText(text,encryptionPassword));} if(await appStorageSet(STORE,text)) setStatus("Saved","saved"); else setStatus("Unsaved","error");}catch(err){console.error(err); setStatus("Save failed","error"); toast("Save failed: "+(err.message||err));}}
function scheduleSave(){if(!state.settings.autosave) return; setStatus("Unsaved","saving"); clearTimeout(saveTimer); saveTimer=setTimeout(saveNow,450)}
async function load(){const raw=await appStorageGet(STORE); if(!raw) return; try{let obj=JSON.parse(raw); if(obj.encrypted){let pw=encryptionPassword||prompt("This data is encrypted. Enter password to unlock:")||""; encryptionPassword=pw; const text=await decryptPkg(obj,pw); obj=JSON.parse(text);} if(!await validatePackage(obj)) throw new Error("Saved data failed validation"); state=await cleanState(obj.payload.state);}catch(err){console.error(err); toast("Saved data could not be loaded. Export backup may be needed.");}}
async function validatePackage(pkg){if(!pkg||typeof pkg!=="object") return false; if(pkg.version&&typeof pkg.version!=="string") return false; if(!pkg.payload||typeof pkg.payload!=="object"||!pkg.payload.state) return false; if(pkg.checksum){const text=JSON.stringify(pkg.payload); const chk=await sha256(text); if(chk!==pkg.checksum) return false;} const s=pkg.payload.state; if(s.version&&typeof s.version!=="string") return false; if(s.data&&typeof s.data!=="object") return true; return !!s.data}
async function cleanState(s){s=cleanPlainObject(s); const out={version:APP_VERSION,settings:{autosave:true,history:true,encryption:false,...cleanPlainObject(s.settings)},data:{}}; out.settings.autosave=!!out.settings.autosave; out.settings.history=!!out.settings.history; out.settings.encryption=!!out.settings.encryption; out.settings.plan=sanitize(s.settings?.plan||"free",20)==="pro"?"pro":"free"; out.settings.licenseKey=sanitize(s.settings?.licenseKey||"",80); out.settings.cloudBackupToken=sanitize(s.settings?.cloudBackupToken||"",200); out.settings.proActivatedAt=sanitize(s.settings?.proActivatedAt||"",40); out.settings.lastCloudBackup=sanitize(s.settings?.lastCloudBackup||"",40); const data=cleanPlainObject(s.data); const keys=Object.keys(SPECIALTY_INDEX||{}); const toLoad=keys.filter(k=>{const sd=data[k]; return sd&&(Array.isArray(sd.leads)&&sd.leads.length||Array.isArray(sd.benchmarks)&&sd.benchmarks.length)}); await ensureSpecialtiesLoaded(toLoad); for(const key of keys){const sd=cleanPlainObject(data[key]); const prev=currentSpec; currentSpec=key; out.data[key]={leads:Array.isArray(sd.leads)?sd.leads.map(cleanLead):[],benchmarks:Array.isArray(sd.benchmarks)?sd.benchmarks.map(cleanBenchmark):[],history:Array.isArray(sd.history)?sd.history.slice(0,500).map(h=>({at:sanitize(h.at,40),leadId:sanitize(h.leadId,80),lead:sanitize(h.lead,120),summary:sanitize(h.summary,1000)})):[]}; currentSpec=prev;} return out}
function renderHome(){const g=$("specialtyGrid"); clear(g); Object.entries(SPECIALTY_INDEX||{}).forEach(([key,s])=>{g.append(e("button",{className:"specialty-card",type:"button",onclick:()=>openSpecialty(key)},[e("b",{textContent:s.emoji}),e("h3",{textContent:s.name}),e("p",{textContent:s.tag})]))})}
async function openSpecialty(key){await loadSpecialty(key); currentSpec=key; const ss=specState(key); if(!ss.leads.length&&SPECIALTIES[key].samples.length) ss.leads=SPECIALTIES[key].samples.map(defaultLead); selectedJobs=new Set(ss.leads.slice(0,3).map(l=>l.id)); $("home").hidden=true; $("tool").hidden=false; ["homeBtn","exportBtn","importBtn","shareBtn","printBtn"].forEach(id=>$(id).hidden=false); $("appTitle").textContent=SPECIALTIES[key].name+" Job Compare"; $("heroTitle").textContent=SPECIALTIES[key].emoji+" "+SPECIALTIES[key].name; $("heroText").textContent=SPECIALTIES[key].tag; switchView("dashboard"); render(); scheduleSave();}
function goHome(){currentSpec=null; $("home").hidden=false; $("tool").hidden=true; ["homeBtn","exportBtn","importBtn","shareBtn","printBtn"].forEach(id=>$(id).hidden=true); $("appTitle").textContent="Specialty Job Compare";}
function renderCore(){renderGuide(); renderCards(); renderSelectors(); renderCompare(); renderChecklist(); renderVolume(); renderBenchmarks(); renderHistory(); renderQuestions(); const leads=specState().leads; $("topLeadScore").textContent=leads.length?String(Math.max(...leads.map(score))):"--";}
function render(opts){if(!currentSpec){renderHome(); return} if(typeof window.__p1Render==="function") return window.__p1Render(opts); renderCore()}
function renderGuide(){const p=$("scoringGuide"); clear(p); const spec=SPECIALTIES[currentSpec]||{}; p.append(e("h2",{textContent:"Scoring criteria guide"}),e("p",{textContent:"Score 1–3 = weak/unclear, 4–6 = acceptable but needs clarification, 7–10 = strong, confirmed, and aligned with this specialty."})); const g=e("div",{className:"grid"}); SCORE_META.forEach(([key,label,weight,icon,items])=>{const c=e("article",{className:"qcard"}); c.append(e("h3",{textContent:`${icon} ${label} (${weight})`})); const ul=e("ul"); items.forEach(x=>ul.append(e("li",{textContent:x}))); c.append(ul); const lens=(SCORING_CONTEXT[currentSpec]||{})[label]; if(lens&&lens.length){const box=e("div",{className:"scoring-lens"}); box.append(e("b",{textContent:`${spec.name||"Specialty"} lens`})); const lu=e("ul"); lens.forEach(x=>lu.append(e("li",{textContent:x}))); box.append(lu); c.append(box)} g.append(c)}); p.append(g)}
function renderScoreInputs(l){const g=$("scoreGrid"); clear(g); SCORE_META.forEach(([key,label,weight,icon])=>{const wrap=e("div"), top=e("div",{className:"rangetop"}), val=e("span",{className:"rangeval",id:key+"Value",textContent:String(l?l[key]:5)}), lab=e("label",{htmlFor:key,textContent:`${icon} ${label} (${weight})`}), inp=e("input",{id:key,type:"range",min:"1",max:"10",step:"1",value:l?l[key]:5,oninput:()=>val.textContent=inp.value}); top.append(lab,val); wrap.append(top,inp); g.append(wrap)})}
function renderCards(){const w=$("jobCards"), leads=specState().leads; clear(w); if(!leads.length){w.append(e("div",{className:"empty"},[e("h3",{textContent:"No job leads yet"}),e("p",{textContent:"Add a lead to start comparing compensation, benchmarks, APP supervision, quality bonuses, risk, and fit."})])); return} leads.forEach(l=>{const c=e("article",{className:"card"}), top=e("div",{className:"cardtop"}), left=e("div"), bad=e("div",{className:"badges"}); bad.append(e("span",{className:"badge",textContent:l.status||"Unknown"})); if(l.hasEquity) bad.append(e("span",{className:"badge green",textContent:"Equity"})); if(l.hasAppSupervision) bad.append(e("span",{className:"badge green",textContent:"APP"})); if(l.hasQualityBonus) bad.append(e("span",{className:"badge green",textContent:"Quality"})); left.append(bad,e("h3",{textContent:l.name||"Untitled lead"}),e("p",{textContent:`${l.location||"Location TBD"} · ${l.jobType||"Unknown"}`})); top.append(left,e("div",{className:"pill",textContent:String(score(l))})); const m=e("div",{className:"metrics"}); [["Total comp estimate",money(total(l))],["Base",money(l.baseSalary)],["Productivity",l.wrvuRate?`$${l.wrvuRate}/unit`:"TBD"],["Commute",l.commute?l.commute+" min":"TBD"]].forEach(([a,b])=>{m.append(e("div",{className:"metric"},[e("small",{textContent:a}),e("strong",{textContent:b})]))}); const actions=e("div",{className:"actions"},[e("button",{className:"btn",type:"button",textContent:"Edit",onclick:()=>openLead(l.id)}),e("button",{className:"primary",type:"button",textContent:"Compare",onclick:()=>{selectedJobs.add(l.id); switchView("compare"); renderSelectors(); renderCompare();}})]); c.append(top,m,actions); w.append(c)})}
function renderSelectors(){const jw=$("compareJobSelect"), cw=$("compareCategorySelect"); clear(jw); clear(cw); specState().leads.forEach(l=>jw.append(e("button",{className:"chip",type:"button",ariaPressed:selectedJobs.has(l.id),textContent:l.name||"Untitled",onclick:()=>{selectedJobs.has(l.id)?selectedJobs.delete(l.id):selectedJobs.add(l.id); renderSelectors(); renderCompare();}}))); CATEGORIES.forEach(([k,lab])=>cw.append(e("button",{className:"chip",type:"button",ariaPressed:selectedCats.has(k),textContent:lab,onclick:()=>{selectedCats.has(k)?selectedCats.delete(k):selectedCats.add(k); renderSelectors(); renderCompare();}})))}
function bestBenchmark(l){const bs=specState().benchmarks; return bs.find(b=>b.region.toLowerCase()===(l.region||"National").toLowerCase())||bs.find(b=>b.region.toLowerCase()==="national")||bs[0]}
function benchmarkSummary(l){const b=bestBenchmark(l); if(!b) return "No benchmark entered"; const t=total(l); const median=b.compP50||0; if(!median) return `Benchmark: ${b.region}, median not entered`; const pct=((t-median)/median*100); return `${pct>=0?"+":""}${pct.toFixed(1)}% vs ${b.region} median`}
function rows(cat,l){const yes=Object.values(l.checklist||{}).filter(v=>v==="Yes").length, totalItems=SPECIALTIES[currentSpec].checklist.length; const b=bestBenchmark(l); const map={summary:[["Overall score",score(l)],["Status",l.status],["Location",l.location||"TBD"],["Job type",l.jobType||"TBD"],["Region",l.region||"National"]],compensation:[["Comp model",l.compModel],["Base salary",money(l.baseSalary)],["Productivity rate",l.wrvuRate?`$${l.wrvuRate}`:"TBD"],["Threshold",num(l.wrvuThreshold)],["Expected productivity",num(l.expectedWrvu)],["Units above threshold",num(bonusUnits(l))],["Bonus cap",l.bonusCap?money(l.bonusCap):"None"],["Estimated productivity bonus",money(bonus(l))],["Productivity note",productivityNote(l)||"—"],["Sign-on bonus (one-time)",money(l.signOn)],["Call pay (annual est.)",money(l.callPay)],["Estimated annual recurring",money(recurringComp(l))],["Est. first-year incl. sign-on",money(firstYearComp(l))]],benchmark:[["Benchmark used",b?`${b.region} · ${b.source||"Source unlabeled"}`:"None"],["Comp median",b?money(b.compP50):"TBD"],["Comp 75th",b?money(b.compP75):"TBD"],["Offer vs median",benchmarkSummary(l)],["Productivity median",b?num(b.prodP50):"TBD"],["Comp/unit median",b&&b.compPerUnitP50?`$${b.compPerUnitP50}`:"TBD"]],equity:[["Available",l.hasEquity?"Yes":"No"],["Annual income",l.hasEquity?money(l.equityAnnualIncome):"N/A"],["Buy-in",l.hasEquity?money(l.equityBuyIn):"N/A"],["Timeline",l.hasEquity?(l.equityTimeline||"TBD"):"N/A"],["Ownership",l.hasEquity?(l.equityOwnership?l.equityOwnership+"%":"TBD"):"N/A"],["Type",l.hasEquity?(l.equityType||"TBD"):"N/A"]],app:[["APP supervision",l.hasAppSupervision?"Yes":"No"],["APP count",l.hasAppSupervision?num(l.appCount):"N/A"],["Comp model",l.hasAppSupervision?l.appCompModel:"N/A"],["Annual supervision pay",l.hasAppSupervision?money(l.appAnnualComp):"N/A"],["Notes",l.hasAppSupervision?(l.appNotes||"TBD"):"N/A"]],quality:[["Quality bonus",l.hasQualityBonus?"Yes":"No"],["Max annual",l.hasQualityBonus?money(l.qualityBonusMax):"N/A"],["Expected payout",l.hasQualityBonus?money(l.qualityBonusExpected):"N/A"],["Difficulty",l.hasQualityBonus?l.qualityDifficulty:"N/A"],["Formula/notes",l.hasQualityBonus?(l.qualityNotes||"TBD"):"N/A"]],volume:SPECIALTIES[currentSpec].volume.map(item=>[item,l.volume[item]||"TBD"]),lifestyle:[["Lifestyle score",l.lifestyleFit+"/10"],["Commute",l.commute?l.commute+" min":"TBD"],["Call",l.call||"TBD"]],risk:[["Risk safety",l.riskFit+"/10"],["Follow-up/red flags",l.followUp||"TBD"]],collaboration:[["Collaborative fit",l.collabFit+"/10"],["Strategic fit",l.strategicFit+"/10"],["Checklist support",`${yes}/${totalItems}`]],proscons:[["Pros",l.pros||"TBD"],["Cons",l.cons||"TBD"],["Follow-up",l.followUp||"TBD"]]}; return map[cat]||[]}
function val(td,v){v=String(v??""); if(v==="Yes")td.append(e("span",{className:"yes",textContent:"Yes"})); else if(v==="No")td.append(e("span",{className:"no",textContent:"No"})); else if(v==="Unknown")td.append(e("span",{className:"unknown",textContent:"Unknown"})); else td.textContent=v}
function renderCompare(){const w=$("compareTableWrap"); clear(w); const ls=specState().leads.filter(l=>selectedJobs.has(l.id)), cs=CATEGORIES.filter(([k])=>selectedCats.has(k)); if(!ls.length||!cs.length){w.append(e("div",{className:"empty"},["Select at least one job and category."])); return} const table=e("table"); table.append(e("caption",{textContent:"Selected job lead comparison"})); const thead=e("thead"), hr=e("tr"); hr.append(e("th",{textContent:"Category"})); ls.forEach(l=>hr.append(e("th",{textContent:l.name||"Untitled"}))); thead.append(hr); const tb=e("tbody"); cs.forEach(([cat,lab])=>{const sec=e("tr",{className:"sectionrow"}); sec.append(e("th",{colSpan:String(ls.length+1),textContent:lab})); tb.append(sec); rows(cat,ls[0]).forEach((r,i)=>{const tr=e("tr"); tr.append(e("td",{textContent:r[0]})); ls.forEach(l=>{const td=e("td"); val(td,rows(cat,l)[i]?.[1]??"TBD"); tr.append(td)}); tb.append(tr)})}); table.append(thead,tb); w.append(table)}
function renderChecklist(){const w=$("checklistMatrix"); clear(w); const leads=specState().leads; const table=e("table"); table.append(e("caption",{textContent:"Specialty checklist by opportunity"})); const hr=e("tr"); hr.append(e("th",{textContent:"Item"})); leads.forEach(l=>hr.append(e("th",{textContent:l.name||"Untitled"}))); table.append(e("thead",{},[hr])); const tb=e("tbody"); SPECIALTIES[currentSpec].checklist.forEach(item=>{const tr=e("tr"); tr.append(e("td",{textContent:item})); leads.forEach(l=>{const td=e("td"), s=e("select",{value:l.checklist[item]||"Unknown",onchange:()=>{l.checklist[item]=s.value; trackChange(l,"Checklist updated: "+item); refreshAfterMutation(["checklist","dashboard"]); scheduleSave();}}); ["Yes","No","Unknown"].forEach(o=>s.append(e("option",{value:o,textContent:o,selected:(l.checklist[item]||"Unknown")===o}))); td.append(s); tr.append(td)}); tb.append(tr)}); table.append(tb); w.append(table)}
function renderVolume(){const w=$("volumeMatrix"); clear(w); const leads=specState().leads; const table=e("table"); table.append(e("caption",{textContent:"Volume/productivity comparison"})); const hr=e("tr"); hr.append(e("th",{textContent:"Metric"})); leads.forEach(l=>hr.append(e("th",{textContent:l.name||"Untitled"}))); table.append(e("thead",{},[hr])); const tb=e("tbody"); SPECIALTIES[currentSpec].volume.forEach(item=>{const tr=e("tr"); tr.append(e("td",{textContent:item})); leads.forEach(l=>{const td=e("td"), inp=e("input",{value:l.volume[item]||"",maxlength:120,onchange:()=>{l.volume[item]=sanitize(inp.value,120); if(item.toLowerCase().includes("wrvu")) l.expectedWrvu=safeNum(inp.value,0,10000000,l.expectedWrvu); trackChange(l,"Volume updated: "+item); refreshAfterMutation(["volume","dashboard","compare"]); scheduleSave();}}); td.append(inp); tr.append(td)}); tb.append(tr)}); table.append(tb); w.append(table)}
function renderBenchmarks(){const st=specState(), regions=[...new Set(["National",...st.benchmarks.map(b=>b.region)])]; const br=$("benchmarkRegion"), bl=$("benchmarkLead"); clear(br); clear(bl); regions.forEach(r=>br.append(e("option",{value:r,textContent:r}))); st.leads.forEach(l=>bl.append(e("option",{value:l.id,textContent:l.name||"Untitled"}))); br.onchange=()=>renderBenchmarkTable(); bl.onchange=()=>renderBenchmarkAnalysis(); renderBenchmarkAnalysis(); renderBenchmarkTable();}
function renderBenchmarkAnalysis(){const w=$("benchmarkAnalysis"); clear(w); const l=specState().leads.find(x=>x.id===$("benchmarkLead").value)||specState().leads[0]; if(!l){w.append(e("div",{className:"empty"},["Add a lead first."]));return} const b=bestBenchmark(l); const items=[["Annual recurring est.",money(recurringComp(l))],["First-year w/ sign-on",money(firstYearComp(l))],["Benchmark",b?`${b.region} · ${b.source||"Unlabeled"}`:"None"],["Median compensation",b?money(b.compP50):"TBD"],["Offer vs median",benchmarkSummary(l)],["Expected productivity",num(l.expectedWrvu)],["Median productivity",b?num(b.prodP50):"TBD"],["APP supervision pay",money(l.appAnnualComp)],["Quality expected",money(l.qualityBonusExpected)]]; items.forEach(([a,bv])=>w.append(e("article",{className:"card"},[e("h3",{textContent:a}),e("p",{textContent:bv})])))}
function renderBenchmarkTable(){const w=$("benchmarkTable"); clear(w); const region=$("benchmarkRegion").value||"National"; const bs=specState().benchmarks.filter(b=>b.region===region||region==="All"); if(!bs.length){w.append(e("div",{className:"empty"},["No benchmarks entered for this region."])); return} const table=e("table"); table.append(e("caption",{textContent:"Benchmark library"})); const head=e("tr"); ["Region","Source","Year","Comp 50th","Comp 75th","Prod 50th","APP median","Quality median","Actions"].forEach(x=>head.append(e("th",{textContent:x}))); table.append(e("thead",{},[head])); const tb=e("tbody"); bs.forEach(b=>{const tr=e("tr"); [b.region,b.source,b.year||"",money(b.compP50),money(b.compP75),num(b.prodP50),money(b.appSupervisionP50),money(b.qualityBonusP50)].forEach(x=>tr.append(e("td",{textContent:x}))); tr.append(e("td",{},[e("button",{className:"btn",textContent:"Edit",onclick:()=>openBenchmark(b.id)})])); tb.append(tr)}); table.append(tb); w.append(table)}
function renderHistory(){const w=$("historyList"); clear(w); const h=specState().history; if(!h.length){w.append(e("div",{className:"empty"},["No negotiation history yet. Save edits to a lead to start tracking changes."])); return} h.slice().reverse().forEach(x=>w.append(e("article",{className:"qcard"},[e("h3",{textContent:x.lead||"Lead"}),e("p",{textContent:`${x.at} · ${x.summary}`})])))}
function questionKey(group,q){return sanitize(group,80)+"||"+sanitize(q,220)}
function renderQuestions(){
  const w=$("questionList");
  clear(w);
  const grouped = EXPANDED_QUESTIONS[currentSpec];
  const leads = specState().leads;
  const intro=e("div",{className:"notice"},["Use these as recruiter/interview/attorney questions. Open a section to view questions; add optional per-lead answers/notes underneath each question."]);
  w.append(intro);
  if(grouped){
    Object.entries(grouped).forEach(([title, qs],idx)=>{
      const d=e("details",{className:"question-details",open:idx===0});
      d.append(e("summary",{textContent:title}));
      (Array.isArray(qs)?qs:[]).forEach(q=>{
        const item=e("div",{className:"question-item"});
        item.append(e("p",{textContent:sanitize(q)}));
        if(leads.length){
          const ag=e("div",{className:"answer-grid"});
          leads.forEach(l=>{
            const key=questionKey(title,q);
            if(!l.diligence) l.diligence={};
            const box=e("div",{className:"answer-box"});
            box.append(e("b",{textContent:l.name||"Untitled lead"}));
            const ta=e("textarea",{maxlength:2000,placeholder:"Answer / notes for this lead",value:l.diligence[key]||"",onchange:()=>{l.diligence[key]=sanitize(ta.value,2000); trackChange(l,"Due diligence answer updated: "+title); scheduleSave();}});
            box.append(ta); ag.append(box);
          });
          item.append(ag);
        }
        d.append(item);
      });
      w.append(d);
    });
    return;
  }
  const qs = SPECIALTIES[currentSpec]?.questions || [];
  (Array.isArray(qs)?qs:[]).forEach(q=>w.append(e("article",{className:"qcard"},[e("p",{textContent:sanitize(q)})])));
}
function setConditional(){$("equityFields").classList.toggle("open",$("hasEquity").checked); $("appFields").classList.toggle("open",$("hasAppSupervision").checked); $("qualityFields").classList.toggle("open",$("hasQualityBonus").checked)}
function openLead(id=null){lastFocus=document.activeElement; const l=id?specState().leads.find(x=>x.id===id):defaultLead(); $("dialogTitle").textContent=id?"Edit "+(l.name||"lead"):"Add lead"; $("leadId").value=l.id; TEXT_FIELDS.forEach(k=>{const el=$(k); if(el) el.value=l[k]||""}); Object.keys(NUM_FIELDS).forEach(k=>{const el=$(k); if(el) el.value=l[k]||""}); BOOL_FIELDS.forEach(k=>$(k).checked=!!l[k]); setConditional(); renderScoreInputs(l); $("deleteLeadBtn").hidden=!id; $("leadBackdrop").classList.add("open"); document.body.classList.add("modal-open"); $("leadDialog").focus(); lastSnapshot[l.id]=JSON.stringify(l)}
function closeModal(){document.querySelectorAll(".backdrop.open").forEach(x=>x.classList.remove("open")); document.body.classList.remove("modal-open"); if(lastFocus&&lastFocus.focus) lastFocus.focus()}
function gatherLead(){const obj={id:$("leadId").value||uid()}; TEXT_FIELDS.forEach(k=>{const el=$(k); if(el) obj[k]=sanitize(el.value,2000)}); Object.entries(NUM_FIELDS).forEach(([k,[min,max]])=>{const el=$(k); obj[k]=safeNum(el?.value,min,max,0); if(el) el.value=obj[k]||""}); BOOL_FIELDS.forEach(k=>obj[k]=$(k).checked); SCORE_META.forEach(([k])=>obj[k]=safeNum($(k).value,1,10,5)); const old=specState().leads.find(x=>x.id===obj.id); obj.checklist=old?old.checklist:{}; obj.volume=old?old.volume:{}; obj.diligence=old?old.diligence:{}; return defaultLead(obj)}
function saveLead(ev){ev.preventDefault(); const form=$("leadForm"); if(!form.checkValidity()){form.reportValidity(); return} const l=gatherLead(), st=specState(); const i=st.leads.findIndex(x=>x.id===l.id); if(i>=0) st.leads[i]=l; else st.leads.push(l); trackChange(l,i>=0?"Lead updated":"Lead created"); selectedJobs.add(l.id); closeModal(); refreshAfterMutation(["dashboard","compare","report","benchmarks"]); scheduleSave()}
function trackChange(l,summary){if(!state.settings.history) return; const before=lastSnapshot[l.id], after=JSON.stringify(l); if(before&&before===after&&summary==="Lead updated") return; specState().history.push({at:new Date().toLocaleString(),leadId:l.id,lead:l.name||"Untitled",summary:sanitize(summary,1000)}); specState().history=specState().history.slice(-500)}
function deleteLead(){const id=$("leadId").value; if(!confirm("Delete this lead?")) return; specState().leads=specState().leads.filter(l=>l.id!==id); selectedJobs.delete(id); closeModal(); refreshAfterMutation(["dashboard","compare","report","benchmarks","checklist","volume"]); scheduleSave()}
function openBenchmark(id=null){lastFocus=document.activeElement; const b=id?specState().benchmarks.find(x=>x.id===id):cleanBenchmark({}); $("benchId").value=b.id; const map={benchRegion:"region",benchSource:"source",benchYear:"year",benchSetting:"setting",benchNotes:"notes"}; Object.entries(map).forEach(([el,k])=>$(el).value=b[k]||""); Object.keys(BENCH_NUM).forEach(k=>{if($(k)) $(k).value=b[k]||""}); $("deleteBenchBtn").hidden=!id; $("benchBackdrop").classList.add("open"); document.body.classList.add("modal-open"); $("benchDialog").focus()}
function saveBenchmark(ev){ev.preventDefault(); if(!$("benchForm").checkValidity()){$("benchForm").reportValidity(); return} const obj={id:$("benchId").value||uid(),region:$("benchRegion").value,source:$("benchSource").value,year:$("benchYear").value,setting:$("benchSetting").value,notes:$("benchNotes").value}; Object.keys(BENCH_NUM).forEach(k=>obj[k]=$(k)?.value); const b=cleanBenchmark(obj), st=specState(); const i=st.benchmarks.findIndex(x=>x.id===b.id); if(i>=0) st.benchmarks[i]=b; else st.benchmarks.push(b); closeModal(); refreshAfterMutation(["benchmarks","dashboard","compare"]); scheduleSave()}
function deleteBenchmark(){const id=$("benchId").value; if(!confirm("Delete this benchmark?")) return; specState().benchmarks=specState().benchmarks.filter(b=>b.id!==id); closeModal(); refreshAfterMutation(["benchmarks","dashboard","compare"]); scheduleSave()}
function switchView(v){document.querySelectorAll(".tab").forEach(t=>t.setAttribute("aria-selected",String(t.dataset.view===v))); document.querySelectorAll(".view").forEach(p=>p.setAttribute("aria-hidden",String(p.id!==v))); if(v==="benchmarks") renderBenchmarks(); if(v==="history") renderHistory();}
async function exportPackage(){const pkg=await makePackage(); const blob=new Blob([JSON.stringify(pkg,null,2)],{type:"application/json"}); return new File([blob],"specialty-job-compare-data.json",{type:"application/json"})}
async function exportData(){const file=await exportPackage(); const a=e("a",{href:URL.createObjectURL(file),download:file.name}); a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function shareData(){try{const file=await exportPackage(); if(navigator.canShare&&navigator.canShare({files:[file]})) await navigator.share({title:"Specialty Job Compare Data",text:"Exported job comparison data",files:[file]}); else await exportData();}catch(err){if(err.name!=="AbortError"){console.error(err); toast("Share failed; downloaded file instead."); await exportData();}}}
async function importData(file){try{const text=await file.text(); const parsed=JSON.parse(text,(k,v)=>forbiddenKeys.has(k)?undefined:v); if(!await validatePackage(parsed)) throw new Error("Invalid or corrupted import package"); const imported=await cleanState(parsed.payload.state); state=imported; renderHome(); if(currentSpec) render({all:true}); scheduleSave(); toast("Import complete and schema-validated.");}catch(err){console.error(err); toast("Import failed: "+(err.message||err));}}
function openSettings(){$("settingEncryption").checked=!!state.settings.encryption; $("settingAutosave").checked=!!state.settings.autosave; $("settingHistory").checked=!!state.settings.history; $("settingPassword").value=encryptionPassword; $("settingsBackdrop").classList.add("open"); document.body.classList.add("modal-open")}
async function saveSettings(){state.settings.encryption=$("settingEncryption").checked; state.settings.autosave=$("settingAutosave").checked; state.settings.history=$("settingHistory").checked; encryptionPassword=$("settingPassword").value||encryptionPassword; closeModal(); await saveNow();}
async function verifyIntegrity(){const pkg=await makePackage(); const ok=await validatePackage(pkg); toast(ok?"Current data integrity verified.":"Integrity verification failed.")}
function resetSample(){if(!confirm("Reset this specialty to sample data?")) return; specState().leads=SPECIALTIES[currentSpec].samples.map(defaultLead); specState().benchmarks=[]; specState().history=[]; selectedJobs=new Set(specState().leads.slice(0,3).map(l=>l.id)); refreshAfterMutation({all:true}); scheduleSave()}

function bindEvents(){document.querySelectorAll(".tab").forEach(t=>t.addEventListener("click",()=>switchView(t.dataset.view),{signal})); $("homeBtn").addEventListener("click",goHome,{signal}); $("addLeadBtn").addEventListener("click",()=>openLead(),{signal}); $("benchmarkQuickBtn").addEventListener("click",()=>openBenchmark(),{signal}); $("addBenchmarkBtn").addEventListener("click",()=>openBenchmark(),{signal}); $("scoringGuideBtn").addEventListener("click",()=>$("scoringGuide").hidden=!$("scoringGuide").hidden,{signal}); $("resetBtn").addEventListener("click",resetSample,{signal}); $("leadForm").addEventListener("submit",saveLead,{signal}); $("benchForm").addEventListener("submit",saveBenchmark,{signal}); $("deleteLeadBtn").addEventListener("click",deleteLead,{signal}); $("deleteBenchBtn").addEventListener("click",deleteBenchmark,{signal}); ["closeLeadBtn","cancelLeadBtn","closeBenchBtn","cancelBenchBtn","closeSettingsBtn","cancelSettingsBtn","closeHelpBtn","okHelpBtn"].forEach(id=>$(id).addEventListener("click",closeModal,{signal})); ["hasEquity","hasAppSupervision","hasQualityBonus"].forEach(id=>$(id).addEventListener("change",setConditional,{signal})); $("exportBtn").addEventListener("click",exportData,{signal}); $("shareBtn").addEventListener("click",shareData,{signal}); $("importBtn").addEventListener("click",()=>$("importFile").click(),{signal}); $("importFile").addEventListener("change",ev=>{const f=ev.target.files[0]; if(f) importData(f); ev.target.value="";},{signal}); $("settingsBtn").addEventListener("click",openSettings,{signal}); $("saveSettingsBtn").addEventListener("click",saveSettings,{signal}); $("verifyIntegrityBtn").addEventListener("click",verifyIntegrity,{signal}); $("helpBtn").addEventListener("click",()=>{$("helpBackdrop").classList.add("open"); document.body.classList.add("modal-open")},{signal}); $("printBtn").addEventListener("click",()=>{if(typeof printReport==="function") printReport(); else window.print();},{signal}); $("clearHistoryBtn").addEventListener("click",()=>{if(confirm("Clear history for this specialty?")){specState().history=[]; renderHistory(); scheduleSave();}},{signal}); document.querySelectorAll(".backdrop").forEach(b=>b.addEventListener("click",ev=>{if(ev.target===b) closeModal()},{signal})); document.addEventListener("keydown",ev=>{if((ev.ctrlKey||ev.metaKey)&&!ev.shiftKey){const k=ev.key.toLowerCase(); if(k==="n"&&currentSpec){ev.preventDefault(); openLead()} if(k==="b"&&currentSpec){ev.preventDefault(); openBenchmark()} if(k==="e"){ev.preventDefault(); shareData()}} if(ev.key==="Escape"){if(document.querySelector(".backdrop.open")) closeModal(); else if(currentSpec&&document.querySelector(".tab[aria-selected='true']")?.dataset.view!=="dashboard") switchView("dashboard"); else if(currentSpec) goHome();}},{signal}); window.addEventListener("beforeunload",()=>abortController.abort(),{once:true})}
window.onerror=(msg,src,line,col,err)=>{console.error("Global error",msg,src,line,col,err); setStatus("Error","error"); toast("An app error occurred. Export data if possible.");};
window.onunhandledrejection=ev=>{console.error("Unhandled rejection",ev.reason); setStatus("Error","error"); toast("An async app error occurred.");};
async function coreInit(){bindEvents(); await loadSpecialtyIndex(); renderHome(); await load(); renderHome(); if(currentSpec){await loadSpecialty(currentSpec); if(typeof applySpecTheme==="function") applySpecTheme(); render({all:true});} registerServiceWorker();}
window.coreInit = coreInit;
window.init = coreInit;
window.bindEvents = bindEvents;
window.recurringComp = recurringComp;
window.firstYearComp = firstYearComp;
window.bonusUnits = bonusUnits;
window.productivityNote = productivityNote;
window.BENCH_NUM = BENCH_NUM;
window.questionKey = questionKey;
window.renderCore = renderCore;
window.refreshAfterMutation = refreshAfterMutation;
